Various updates from ages ago

diff --git a/wordshell b/wordshell
--- a/wordshell
+++ b/wordshell
@@ -1,13 +1,22 @@
 #!/bin/bash
 # Note - if you change that path to bash, then you should also change it in the configuration section below
 
-VERSION="1.3.140 (2017-12-01)"
+VERSION="1.3.136 (2016-06-18)"
 
 # (c) David Anderson 2011-
+# With modifications by mikeybeck (2016-2017, 2020)
 #
-# https://github.com/DavidAnderson684/wordshell
+# http://wordshell.net / contact@wordshell.net
 #
-# Licence: https://github.com/DavidAnderson684/wordshell/blob/master/LICENSE
+# Licence: http://wordshell.net/support/manual/wordshell-licence/
+#
+# Please do share your patches with me. I prefer then in "diff -uNr" format (please also specify the version against which you are patching).
+
+# mikeybeck's mods:
+# 05/16: Addition of --no-maintenance mode, which prevents site from going into maintenance mode when updating plugins.  (not recommended but y'know...)
+# 06/16: Made remote controller local only so I can make changes (no longer fetches from Amazon s3)
+# 06/17: Added numerical index to plugin list to make selection/specification easier
+
 
 # * * * BEGIN CONFIGURATION * * * #
 
@@ -89,9 +98,9 @@ EXCLUDE_GLOB_FTP="wponlinebackup/tmp/*"
 # Note that if you do not have rsync installed then this next line is totally ignored
 EXCLUDE_GLOB_RSYNC="wponlinebackup/tmp/*"
 
-# Where to fetch a wp-wordshell-controller.php script of sufficiently high protocol from
+# Where to fetch a wp-wordshell-controller.php script of sufficiently high protocol from (locally)
 REMOTE_MANAGER_MINIMUM_PROTOCOL=22
-REMOTE_MANAGER_FROM="https://wordshellnet.s3.amazonaws.com/wp-wordshell-controller.php.$REMOTE_MANAGER_MINIMUM_PROTOCOL"
+REMOTE_MANAGER_FROM="$WORKDIR/wp-wordshell-controller.php"
 
 SELINUX=0
 [[ $UNAME = "Linux" ]] && selinuxenabled 2>/dev/null && SELINUX=1
@@ -455,6 +464,11 @@ wordshell mysite,@mygroup,-site2,-@group2,site3 --listsites
 The above command would include the site mysite, then the sites in group mygroup, then remove site2 and all sites in group2, and finally add in site3.
 
 The default working directory is $WORKDIR and the default configuration file is $CONFIGFILE.
+
+${BOLD}Extra options added by mikeybeck:${OFFBOLD}
+--no-maintenance    :	Prevents WordPress going into maintenance mode [when plugin/theme is being updated].  (NOT RECOMMENDED, but y'know...')
+--removecontroller  :	Deletes remote wp-wordshell-controller.php file.
+--filefindmode      :	Searches for remote filenames using regex (e.g. --filefindmode=.*txt to find all filenames containing 'txt', or --findfilemode=.*\.log to find all .log files)
 "
 exit 0;
 fi
@@ -735,6 +749,14 @@ function parse_option() {
 	elif [[ $i = "--ignorenamechange" ]]; then IGNORENAMECHANGE=1
 	elif [[ $i = "--ignoremodifications" ]]; then IGNOREMODIFICATIONS=1
 	elif [ "$i" = "--lftpdryrun" ]; then LFTPDRYRUN=1
+	# Below options added by mikeybeck
+	elif [ "$i" = "--no-maintenance" ]; then NOMAINTENANCE=1
+	elif [ "$i" = "--removecontroller" ]; then mode_switch "removecontroller"
+	elif [[ $i =~ ^--filefindmode=(.*)$ ]]; then mode_switch "filefindmode"; FILEFINDREGEX=${BASH_REMATCH[1]};
+	elif [[ $i =~ ^--filefindinmode=(.*)$ ]]; then mode_switch "filefindinmode"; FILEFINDREGEX=${BASH_REMATCH[1]};
+	elif [[ $i =~ ^--testclimode=(.*)$ ]]; then mode_switch "testclimode"; CLICMD=${BASH_REMATCH[1]};
+	##elif [ "$i" = "--testclimode" ]; then mode_switch "testclimode"; CLICMD=${BASH_REMATCH[1]};
+#	elif [ "$i" = "--testingmode" ]; then mode_switch "testingmode"
 	elif [ -n "$i" ]; then options_abort "Unknown option: $i"
 	#else echo "???: $i"
 	fi
@@ -3193,6 +3215,7 @@ function setup_remote_manager() {
 	# $2 = flags:
 	#   nononce means do not return a nonce (no call is going to be made); simply make sure we are set up
 	#   earlyping means to use the 'earlyping' RPC instead of ping; does not require WordPress to be alive; you should also always specify nononce with this since the remote end will not be able to update its own nonces
+	#   purgecontroller means to delete entire contents of file - added by mikeybeck - REMOVED/UPDATED
 	# Returns 0 upon success, othersize non-zero; also sets the next valid REMOTEMANAGER_NONCE (this is the one to put in wpm-a), REMOTEMANAGER_KEY, SITEURL_HOST and SITEURL_LOCAL and otthers used internally: REMOTEMANAGER_COUNTER, REMOTEMANAGER_UPLOADTIME
 	# Sets GET_REMOTE_MESSAGE if there was a problem
 	local SETUP_RM_FLAGS=$2
@@ -3231,7 +3254,16 @@ function setup_remote_manager() {
 		echo "define('WORDSHELL_FTP_PASS', '$QUOTPASS');" >>$CONTROL_TMP
 		echo "define('WORDSHELL_FTP_HOST', '$FTPHOST'); ?>" >>$CONTROL_TMP
 	fi
-	cat ../wp-wordshell-controller.php >>$CONTROL_TMP
+
+	#if [[ $SETUP_RM_FLAGS =~ purgecontroller ]]; then
+	#	echo "purging..."
+#		echo "" > $CONTROL_TMP
+#	else
+		cat ../wp-wordshell-controller.php >>$CONTROL_TMP
+#	fi
+
+
+
 	if [[ $ACCESSMETHOD = "file" ]]; then
 		[[ $DEBUG -ge 1 ]] && ws_event_info "Copy across remote controller (filesystem)"
 		cp $COPYOPT $CONTROL_TMP "$FILEDIR/wp-wordshell-controller.php"
@@ -3568,7 +3600,7 @@ function rpc_mirror_get() {
 					[[ $DEBUG -ge 1 ]] && ws_event_info "$LMIRROR_DIR/$LFILE_NAME out of date: will fetch"
 					remotecli_process "getfile:$LFILE_NAME" tellfile
 					local LDIR_TMP=$REMOTECLI_OUTPUT
-					local GET_ANS="`dd if=$LDIR_TMP bs=15 count=1 of=/dev/stdout 2>/dev/null`"
+					local GET_ANS='`dd if=$LDIR_TMP bs=15 count=1 of=/dev/stdout 2>/dev/null`' #Single quotes here so sublime text higlighting doesn't break
 					if [[ $GET_ANS = "AUTHOK:CANTREAD" ]]; then
 						ws_event_warning "$SITE: $LINE: Could not download file (error: file not readable)"
 						rm -f $LDIR_TMP
@@ -5054,6 +5086,138 @@ fi
 
 # Setup finished: now we have the site and its access details, and they are sanity-checked; we can start processing most modes
 
+
+
+################################################
+#
+# Stuff added by mikeybeck
+#
+################################################
+
+
+
+
+function remotecmd() {
+	#
+	#local LISTOFFILES=$1
+
+
+	if [ -z "$2" ]; then
+#		if [[ $MODE = "filefindmode" ]]; then
+
+		[[ $DEBUG -ge 1 ]] && ws_event_info "Remote cmd = filefind:$1"
+		#exit
+		remotecli_process "filefind:$1"
+#		fi
+	else
+		[[ $DEBUG -ge 1 ]] && ws_event_info "Remote cmd = filefind:$1:$2"
+		#exit
+		remotecli_process "filefind:$1:$2"
+	fi
+
+#	if [[ $MODE = "filefindinmode" ]]; then
+#		remotecli_process "filefindin:$1"
+#	fi
+		#if [[ $REMOTECLI_OUTPUT =~ :DELETED: ]]; then
+		#	[[ $DEBUG -ge 2 ]] && ws_event_info "Successfully deleted file: $DELTHISFILE"
+		#else
+		#	[[ $DEBUG -ge 1 ]] && ws_event_warning "Tried to delete file $DELTHISFILE, but failed (output was: $REMOTECLI_OUTPUT)"
+		#fi
+	#fi
+}
+
+function remotecli() {
+	#
+	#local LISTOFFILES=$1
+
+
+	if [ -z "$2" ]; then
+
+		[[ $DEBUG -ge 1 ]] && ws_event_info "Remote cmd = remotecli:$1"
+
+		remotecli_process "remotecli:$1"
+
+	fi
+
+}
+
+
+
+# Added by mikeybeck
+if [[ $MODE = "testclimode" ]]; then
+
+
+#	if [[ $FILEFINDREGEX = "*" ]]; then
+#		REGEX=$FILEFINDREGEX
+#	fi
+
+#	echo "Searching $SITEURL for files"
+#	echo  "Using regex /$REGEX/"
+	echo "running cmd... $CLICMD"
+
+	remotecli $CLICMD
+	exit
+
+fi
+
+# Added by mikeybeck
+if [[ $MODE = "filefindmode" ]]; then
+
+
+	# Check for caret ^ symbol
+	if [[ $FILEFINDREGEX == *"^"* ]]; then
+		# Do search inside files using string after ^
+		FINDSTRING=${FILEFINDREGEX#*^}
+		REGEX=${FILEFINDREGEX%^*}
+
+		# If regex is * then search for everything
+		if [[ $REGEX = "*" ]]; then
+				REGEX="[\s\S]*"
+		fi
+
+		echo "Searching $SITEURL for files"
+		echo "Using regex /$REGEX/"
+		echo "Containing string: $FINDSTRING"
+        ## .*txt would find all txt files
+		remotecmd $REGEX $FINDSTRING
+		exit
+	fi
+
+	# If regex is * then search for everything
+	if [[ $FILEFINDREGEX = "*" ]]; then
+			REGEX="[\s\S]*"
+	else
+		REGEX=$FILEFINDREGEX
+	fi
+
+	echo "Searching $SITEURL for files"
+	echo  "Using regex /$REGEX/"
+    # .*txt would find all txt files
+	remotecmd $REGEX
+	exit
+
+fi
+
+
+
+# Delete remote wp controller.  Added by mikeybeck
+if [[ $MODE = "removecontroller" ]]; then
+				ftp_deletefile 'wp-wordshell-controller.php'
+				echo "Remote wp-wordshell-controller.php file deleted!"
+				#setup_remote_manager $REMOTE_MANAGER_MINIMUM_PROTOCOL purgecontroller
+				exit
+fi
+
+
+
+
+
+################################################
+#
+# END of stuff added by mikeybeck
+#
+################################################
+
 # Apply the filters from --fast (exit if nothing to do) (these are never set with --core)
 if [[ ( $MODE = "delete" || $MODE = "normal" || $MODE = "restore" || $MODE = "rollback" || $MODE = "list" || $MODE = "checkmodifications" ) && ( $FAST -eq 1 ) ]]; then
 	if [[ ! -e "$WORKINGDIR_FULL/current/$SITE/$METAMODE_DIR/$PLUGIN" ]]; then
@@ -5236,7 +5400,7 @@ function sync_core() {
 		local THEVERSION=$REMOTE_WPVERSION
 	else
 		remotecli_process wpversion setvar
-		if [[ ! $REMOTECLI_OUTPUT =~ AUTHOK:WPVERSION:([0-9](\.[0-9]+)+(-(alpha|beta|RC[0-9]?(-[0-9]+)))?)$ ]]; then
+		if [[ ! $REMOTECLI_OUTPUT =~ ^AUTHOK:WPVERSION:([0-9](\.[0-9]+)+(-(alpha|beta|RC[0-9]?(-[0-9]+)))?)$ ]]; then
 			ws_event_error "Could not find the remote version number (output was: $REMOTECLI_OUTPUT)"
 			return
 		fi
@@ -5761,6 +5925,9 @@ function show_theentities() {
 	# Input: make sure we are cd-ed into a directory of the appropriate (METAMODE) entities
 	# $1 : slug to match - or if empty, show them all
 	# At present, use of this parameter (i.e. non-empty) implies we are in list mode, so we can assume that
+
+	# mikeybeck's mods: save current entities list to file with index numbers
+
 	local SHOWONLY=$1
 	[[ $DEBUG -ge 1 ]] && ws_event_debug "show_theentities: $SHOWONLY (pwd: `pwd`, caller: `caller`)"
 	FOUNDWANTED=0
@@ -5773,28 +5940,58 @@ function show_theentities() {
 		IFS="
 	"
 		# Find the plugins
+		echo -n > "../entities.txt"
+		ENT_INDEX=0
+		#ENT_NUM=00
 		for i in `find . -maxdepth 1 -iregex './[a-z0-9].*' | sort`; do
 			# This could match the directory name (e.g. "akismet" from plugin akismet/akismet.php) or the file name (e.g. hello.php for "Hello Dolly")
 			PLUGDIR=`echo "$i" | cut -d/ -f2`
+
+			if (( $ENT_INDEX < 10 )); then
+				ENT_NUM="0${ENT_INDEX}"
+			else
+				ENT_NUM="$ENT_INDEX"
+			fi
+
 			# Plugins in directories
 			if [[ -d $i ]]; then
 				# Enter the plugin's directory
 				ws_pushd "$i"
+
+				if [[ $(showentity_thisdir "$SHOWONLY") ]]; then
+					# Print entity index number
+					echo -n "$ENT_NUM  "
+					# Add entity number and remove ./ from plugin name
+					echo "$ENT_NUM" ${i#./} >> ../../entities.txt
+					ENT_INDEX=$((ENT_INDEX+1))
+				fi
+
 				# See what's in this directory
 				showentity_thisdir "$SHOWONLY"
 				ws_popd
 			# Plugins in files
 			elif [[ $METAMODE = "plugin" && $i =~ .*\.php$ ]]; then
+
+				if [[ $(showentity_thisdir "$SHOWONLY" file) ]]; then
+					# Print entity index number
+					echo -n "$ENT_NUM  "
+					echo "$ENT_NUM" file >> ../../entities.txt
+					ENT_INDEX=$((ENT_INDEX+1))
+				fi
+
 				showentity_thisdir "$SHOWONLY" file
 			else
 				[[ $DEBUG -ge 1 ]] && ws_event_notice "$i: Unknown entity found in ${METAMODE}s directory"
 			fi
+
 		done
 		if [[ $WARNMISSING -eq 1 && $FOUNDWANTED -eq 0 && $MODE = "list" ]]; then
 			ws_event_warning "no ${METAMODE} found (site: $SITE)"
 		fi
 		IFS="$OLDIFS"
 	fi
+
+	echo $PWD
 }
 
 HAVESHOWNPLUGS=0
@@ -5944,6 +6141,9 @@ while [[ ( -z $PLUGIN || ! -e "$PLUGIN" ) && $MODE != "install" && $PLUGIN_OR_TH
 	fi
 	if [ $HAVESHOWNPLUGS -eq 0 ]; then
 		echo "${METAMODE_CAP}s in use on this site:"
+
+		#TODO: Get number of directories in local plugin folder and show progress bar after each plugin is checked
+
 		show_theentities
 		HAVESHOWNPLUGS=1
 	fi
@@ -5953,12 +6153,17 @@ while [[ ( -z $PLUGIN || ! -e "$PLUGIN" ) && $MODE != "install" && $PLUGIN_OR_TH
 	read -p "${METAMODE_CAP} to $PLACTION (prepend with changelog/description to show info; Ctrl-C to quit): " PLUGIN
 	CREGEX="^c(hangelog)? (\S+)$"
 	DREGEX="^d(escription)? (\S+)$"
+	INT='^[0-9]+$'
 	if [[ $PLUGIN =~ $CREGEX ]]; then
 		get_api_changelog ${BASH_REMATCH[2]} changelog
 		PLUGIN=""
 	elif [[ $PLUGIN =~ $DREGEX ]]; then
 		get_api_changelog ${BASH_REMATCH[2]} description
 		PLUGIN=""
+	# Mikey's mods: Match plugin/theme number with number from entities file; get plugin name from there
+	elif [[ $PLUGIN =~ $INT ]]; then
+		PLUGIN=`sed -n "s/$PLUGIN //p" ../entities.txt`
+		echo "$PLUGIN" "selected"
 	elif [ ! -d "$PLUGIN" ]; then
 		ws_event_error "${METAMODE_CAP} not found, please try again"
 		PLUGIN=""
@@ -6110,15 +6315,9 @@ if [[ $FOUNDPLUG -eq 1 && ( ( $MODE = "normal" && $ROLLBACKTIME = "x" && $IGNORE
 				LOCAL_COPY_TO_EXAMINE="../../../current/$SITE/core"
 				# Only -b -r are POSIX. But -u and -N are in Mac OS X, FreeBSD and GNU and OpenSolaris (2009). -B -d and are in MacOSX/FreeBSD/GNU
 				DIFF_OPTIONS="-Bburd"
-				# Obviously, this isn't proper internationalisation, and only works with English/French
-				$DIFF -Bburd . "$LOCAL_COPY_TO_EXAMINE" | grep -v "^Only in" | grep -v "^Seulement dans" >$DIFFTMP
-				# Diff will return 1 if there are differences (including 'Only in...'); grep -v will return 1 if there were suppressed lines, or 0 if there was not (we don't expect any other code)
-				# Dec 2016 - now we just check for no output, because of the double grep
-				if [[ -s $DIFFTMP ]]; then
-					DIFF_RET=1
-				else
-					DIFF_RET=0
-				fi
+				$DIFF -Bburd . "$LOCAL_COPY_TO_EXAMINE" | grep -v "^Only in " >$DIFFTMP
+				# Diff will return 1 if there are differences (including 'Only in...'); grep will return 0 if there was output, or 1 if there was (we don't expect any other code)
+				DIFF_RET=$((1-$?))
 				AUTOPATCH_STRIP=6
 			else
 				# Back to working directory. The moving around is because it seemed to silence a patch warning.
@@ -6147,7 +6346,7 @@ if [[ $FOUNDPLUG -eq 1 && ( ( $MODE = "normal" && $ROLLBACKTIME = "x" && $IGNORE
 				[[ $MODE != "checkmodifications" ]] && echo -n "${BOLD}WARNING:${OFFBOLD} "
 				[[ $MODE != "checkmodifications" || $DEBUG -ge 1 ]] && echo "$SITE: $PLUGIN: The $METAMODE has apparently been modified from its original state."
 				# $DIFFACTION is emptied above
-				[[ $DEBUG -ge 1 ]] && ws_event_debug "Diff command was: $DIFF $DIFF_OPTIONS . $LOCAL_COPY_TO_EXAMINE ; cd = `pwd` ; return code = $DIFF_RET"
+				[[ $DEBUG -ge 1 ]] && ws_event_debug "Diff command was: $DIFF $DIFF_OPTIONS . $LOCAL_COPY_TO_EXAMINE ; cd = `pwd`"
 				unset DIFFACTION
 				if [ $AUTOPATCH -eq 1 ]; then
 					DIFFACTION="p"
@@ -6671,7 +6870,12 @@ if [[ $METAMODE != "content" && ( $METAMODE != "core" || $MODE != "install" ) ]]
 		if [[ $METAMODE = "core" && $MODE = "normal" && $FILEMETHOD -eq 0 ]]; then
 			maintenance_mode waitclear
 		else
-			maintenance_mode enterwait
+			if [[ $NOMAINTENANCE == 1 ]]; then
+				echo "--no-maintenance mode selected!"
+				echo "Not bothering with maintenance mode.  Would be entering now though."
+			else
+				maintenance_mode enterwait
+			fi
 		fi
 	else
 		ws_event_info "Dry run mode: skipped putting site into maintenance mode"
